# ============================================================================
# hyprsunset -- filtro de luz azul -- https://wiki.hypr.land/hypr-ecosystem/user/hyprsunset/
# ============================================================================

max-gamma = 100

profile {
    time = 8:00
    identity = true
}

profile {
    time = 20:00
    temperature = 4500
    gamma = 1.0
}

profile {
    time = 23:00
    temperature = 3500
    gamma = 0.9
}
